// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: alive.sql

package database

import (
	"context"
)

const alive = `-- name: Alive :one
SELECT 1
`

func (q *Queries) Alive(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, alive)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
