// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: subscribes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscribe = `-- name: CreateSubscribe :one
INSERT INTO subscribes (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateSubscribeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateSubscribe(ctx context.Context, arg CreateSubscribeParams) (Subscribe, error) {
	row := q.db.QueryRowContext(ctx, createSubscribe,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i Subscribe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteSubscribe = `-- name: DeleteSubscribe :exec
DELETE FROM subscribes WHERE id = $1 AND user_id = $2
`

type DeleteSubscribeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSubscribe(ctx context.Context, arg DeleteSubscribeParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscribe, arg.ID, arg.UserID)
	return err
}

const getSubscribe = `-- name: GetSubscribe :many
SELECT id, created_at, updated_at, user_id, feed_id FROM subscribes WHERE user_id = $1
`

func (q *Queries) GetSubscribe(ctx context.Context, userID uuid.UUID) ([]Subscribe, error) {
	rows, err := q.db.QueryContext(ctx, getSubscribe, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscribe
	for rows.Next() {
		var i Subscribe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
