// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: subscribes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscribe = `-- name: CreateSubscribe :one
INSERT INTO subscribes (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateSubscribeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateSubscribe(ctx context.Context, arg CreateSubscribeParams) (Subscribe, error) {
	row := q.db.QueryRowContext(ctx, createSubscribe,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i Subscribe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
